version: '3.1'
services:
  stats-db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  stats-server:
    build: stat
    container_name: stat_svc
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stat
      - DB_PASS=postgres
      - DB_USERNAME=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
