version: '3.1'
services:
  stats-db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  stats-server:
    build: stat
    container_name: stat_svc
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stat
      - DB_PASS=postgres
      - DB_USERNAME=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



  ewm-service:
    build: ewm
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm_db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db


  ewm-db:
    container_name: ewm_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

